### ISSUE TITLE
Cannot find definitions with haskell-language-server and darcs

### ISSUE THREAD

**Issue by alexDarcy** [joaotavora/eglot#741]
* Server used:               haskell-language-server
* Emacs version:             28.0.50
* Operating system:          FreeBsd 13.0
* Eglot version:             1.7
* Eglot installation method:       straight.el
* Using Doom:                No

#### LSP transcript - M-x eglot-events-buffer (mandatory unless Emacs inoperable)

     
```lisp
[client-request] (id:1) Sun Sep 12 16:27:20 2021:
(:jsonrpc "2.0" :id 1 :method "initialize" :params
	  (:processId 17917 :rootPath "/usr/home/alex/test/" :rootUri "file:///usr/home/alex/test" :initializationOptions #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data
																	())
		      :capabilities
		      (:workspace
		       (:applyEdit t :executeCommand
				   (:dynamicRegistration :json-false)
				   :workspaceEdit
				   (:documentChanges :json-false)
				   :didChangeWatchedFiles
				   (:dynamicRegistration t)
				   :symbol
				   (:dynamicRegistration :json-false)
				   :configuration t)
		       :textDocument
		       (:synchronization
			(:dynamicRegistration :json-false :willSave t :willSaveWaitUntil t :didSave t)
			:completion
			(:dynamicRegistration :json-false :completionItem
					      (:snippetSupport :json-false)
					      :contextSupport t)
			:hover
			(:dynamicRegistration :json-false :contentFormat
					      ["plaintext"])
			:signatureHelp
			(:dynamicRegistration :json-false :signatureInformation
					      (:parameterInformation
					       (:labelOffsetSupport t)
					       :activeParameterSupport t))
			:references
			(:dynamicRegistration :json-false)
			:definition
			(:dynamicRegistration :json-false :linkSupport t)
			:declaration
			(:dynamicRegistration :json-false :linkSupport t)
			:implementation
			(:dynamicRegistration :json-false :linkSupport t)
			:typeDefinition
			(:dynamicRegistration :json-false :linkSupport t)
			:documentSymbol
			(:dynamicRegistration :json-false :hierarchicalDocumentSymbolSupport t :symbolKind
					      (:valueSet
					       [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26]))
			:documentHighlight
			(:dynamicRegistration :json-false)
			:codeAction
			(:dynamicRegistration :json-false :codeActionLiteralSupport
					      (:codeActionKind
					       (:valueSet
						["quickfix" "refactor" "refactor.extract" "refactor.inline" "refactor.rewrite" "source" "source.organizeImports"]))
					      :isPreferredSupport t)
			:formatting
			(:dynamicRegistration :json-false)
			:rangeFormatting
			(:dynamicRegistration :json-false)
			:rename
			(:dynamicRegistration :json-false)
			:publishDiagnostics
			(:relatedInformation :json-false))
		       :experimental #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data
						   ()))))
[stderr] No 'hie.yaml' found. Try to discover the project type!
[stderr] Run entered for haskell-language-server-wrapper(haskell-language-server-wrapper) Version 1.2.0.0 x86_64 ghc-8.10.7
[stderr] Current directory: /usr/home/alex/test
[stderr] Operating system: freebsd
[stderr] Arguments: ["--lsp"]
[stderr] Cradle directory: /usr/home/alex/test
[stderr] Cradle type: Default
[stderr] 
[stderr] 
[stderr] Tool versions found on the $PATH
[stderr] cabal:		3.4.0.0
[stderr] stack:		2.7.1
[stderr] ghc:		8.10.7
[stderr] 
[stderr] 
[stderr] Consulting the cradle to get project GHC version...
[stderr] Project GHC version: 8.10.7
[stderr] haskell-language-server exe candidates: ["haskell-language-server-8.10.7","haskell-language-server"]
[stderr] Launching haskell-language-server exe at:/usr/local/bin/haskell-language-server-8.10.7
[stderr] nil
[stderr] haskell-language-server version: 1.2.0.0 (GHC: 8.10.7) (PATH: /usr/local/bin/haskell-language-server)
[stderr] Starting (haskell-language-server)LSP server...
[stderr]   with arguments: GhcideArguments {argsCommand = LSP, argsCwd = Nothing, argsShakeProfiling = Nothing, argsTesting = False, argsExamplePlugin = False, argsDebugOn = False, argsLogFile = Nothing, argsThreads = 0, argsProjectGhcVersion = False}
[stderr]   with plugins: [PluginId "pragmas",PluginId "floskell",PluginId "fourmolu",PluginId "tactics",PluginId "ormolu",PluginId "stylish-haskell",PluginId "retrie",PluginId "brittany",PluginId "class",PluginId "haddockComments",PluginId "eval",PluginId "importLens",PluginId "refineImports",PluginId "moduleName",PluginId "hlint",PluginId "splice",PluginId "ghcide-hover-and-symbols",PluginId "ghcide-code-actions-imports-exports",PluginId "ghcide-code-actions-type-signatures",PluginId "ghcide-code-actions-bindings",PluginId "ghcide-code-actions-fill-holes",PluginId "ghcide-completions",PluginId "ghcide-type-lenses",PluginId "ghcide-core"]
[stderr]   in directory: /usr/home/alex/test
[stderr]  Starting LSP server...
[stderr] If you are seeing this in a terminal, you probably should have run WITHOUT the --lsp option!
[stderr] Started LSP server in 0.00s
[stderr] setInitialDynFlags cradle: Cradle {cradleRootDir = "/usr/home/alex/test", cradleOptsProg = CradleAction: Default}
[stderr] 2021-09-12 16:27:21.167236536 [ThreadId 5] INFO hls:	Registering ide configuration: IdeConfiguration {workspaceFolders = fromList [NormalizedUri (-6096344772590460870) "file:///usr/home/alex/test"], clientSettings = hashed (Just (Object (fromList [])))}
[server-reply] (id:1) Sun Sep 12 16:27:21 2021:
(:result
 (:capabilities
  (:foldingRangeProvider :json-false :hoverProvider t :typeDefinitionProvider t :colorProvider :json-false :renameProvider :json-false :declarationProvider :json-false :executeCommandProvider
			 (:commands
			  ["17926:tactics:tacticsAutoCommand" "17926:tactics:tacticsIntrosCommand" "17926:tactics:tacticsDestructCommand" "17926:tactics:tacticsDestructPunCommand" "17926:tactics:tacticsHomomorphismCommand" "17926:tactics:tacticsDestructLambdaCaseCommand" "17926:tactics:tacticsHomomorphismLambdaCaseCommand" "17926:tactics:tacticsDestructAllCommand" "17926:tactics:tacticsUseDataConCommand" "17926:tactics:tacticsRefineCommand" "17926:tactics:tacticsBeginMetaprogramCommand" "17926:tactics:tacticsRunMetaprogramCommand" "17926:tactics:wingman.emptyCase" "17926:retrie:retrieCommand" "17926:class:addMinimalMethodPlaceholders" "17926:eval:evalCommand" "17926:importLens:ImportLensCommand" "17926:refineImports:RefineImportLensCommand" "17926:moduleName:updateModuleName" "17926:hlint:applyOne" "17926:hlint:applyAll" "17926:splice:expandTHSpliceInplace" "17926:ghcide-completions:extendImport" "17926:ghcide-type-lenses:typesignature.add"])
			 :documentRangeFormattingProvider t :documentHighlightProvider t :implementationProvider :json-false :completionProvider
			 (:resolveProvider :json-false :triggerCharacters
					   ["."])
			 :workspace
			 (:workspaceFolders
			  (:supported t :changeNotifications t))
			 :definitionProvider t :documentFormattingProvider t :referencesProvider t :selectionRangeProvider :json-false :codeLensProvider
			 (:resolveProvider :json-false :workDoneProgress :json-false)
			 :documentSymbolProvider t :textDocumentSync
			 (:save nil :change 2 :openClose t)
			 :workspaceSymbolProvider t :codeActionProvider t))
 :id 1 :jsonrpc "2.0")
[client-notification] Sun Sep 12 16:27:21 2021:
(:jsonrpc "2.0" :method "initialized" :params #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data
							    ()))
[client-notification] Sun Sep 12 16:27:21 2021:
(:jsonrpc "2.0" :method "textDocument/didOpen" :params
	  (:textDocument
	   (:uri "file:///usr/home/alex/test/test.hs" :version 0 :languageId "haskell" :text "module main where\n\nmyFunc = print \"coucou\"\n\nmain = do\n  myFuc\n")))
[client-notification] Sun Sep 12 16:27:21 2021:
(:jsonrpc "2.0" :method "workspace/didChangeConfiguration" :params
	  (:settings nil))
[stderr] 2021-09-12 16:27:21.176135106 [ThreadId 47] INFO hls:	Consulting the cradle for "test.hs"
[stderr] 2021-09-12 16:27:21.17625225 [ThreadId 47] WARNING hls:	No [cradle](https://github.com/mpickering/hie-bios#hie-bios) found for test.hs.
[stderr]  Proceeding with [implicit cradle](https://hackage.haskell.org/package/implicit-hie).
[stderr] You should ignore this message, unless you see a 'Multi Cradle: No prefixes matched' error.
[server-request] (id:0) Sun Sep 12 16:27:21 2021:
(:id 0 :method "client/registerCapability" :params
     (:registrations
      [(:id "globalFileWatches" :method "workspace/didChangeWatchedFiles" :registerOptions
	    (:watchers
	     [(:kind 7 :globPattern "**/*.hs")
	      (:kind 7 :globPattern "**/*.hs-boot")
	      (:kind 7 :globPattern "**/*.lhs")
	      (:kind 7 :globPattern "**/*.lhs-boot")]))])
     :jsonrpc "2.0")
[client-reply] (id:0) Sun Sep 12 16:27:21 2021:
(:jsonrpc "2.0" :id 0 :result nil)
[server-notification] Sun Sep 12 16:27:21 2021:
(:method "window/logMessage" :params
	 (:message "lsp:configuration parse error. NotificationMessage {_jsonrpc = \"2.0\", _method = SWorkspaceDidChangeConfiguration, _params = DidChangeConfigurationParams {_settings = Null}} \"parsing Config failed, expected Object, but encountered Null\"" :type 1)
	 :jsonrpc "2.0")
[stderr] Output from setting up the cradle Cradle {cradleRootDir = "/usr/home/alex/test", cradleOptsProg = CradleAction: Default}
[stderr] 2021-09-12 16:27:21.287820685 [ThreadId 47] INFO hls:	Using interface files cache dir: /home/alex/.cache/ghcide/main-da39a3ee5e6b4b0d3255bfef95601890afd80709
[stderr] 2021-09-12 16:27:21.287989746 [ThreadId 47] INFO hls:	Making new HscEnv[main]
[server-notification] Sun Sep 12 16:27:21 2021:
(:method "textDocument/publishDiagnostics" :params
	 (:diagnostics
	  [(:range
	    (:end
	     (:character 11 :line 0)
	     :start
	     (:character 7 :line 0))
	    :message "parse error on input ‘main’" :severity 1 :source "parser")]
	  :uri "file:///usr/home/alex/test/test.hs" :version 0)
	 :jsonrpc "2.0")
[client-request] (id:2) Sun Sep 12 16:27:21 2021:
(:jsonrpc "2.0" :id 2 :method "textDocument/hover" :params
	  (:textDocument
	   (:uri "file:///usr/home/alex/test/test.hs")
	   :position
	   (:line 0 :character 0)))
[client-request] (id:3) Sun Sep 12 16:27:21 2021:
(:jsonrpc "2.0" :id 3 :method "textDocument/documentHighlight" :params
	  (:textDocument
	   (:uri "file:///usr/home/alex/test/test.hs")
	   :position
	   (:line 0 :character 0)))
[stderr] 2021-09-12 16:27:21.528001973 [ThreadId 86] INFO hls:	finish: Wingman.getMetaprogramsAtSpan.TypeCheck (took 0.00s)
[server-reply] (id:2) Sun Sep 12 16:27:21 2021:
(:result nil :id 2 :jsonrpc "2.0")
[server-reply] (id:3) Sun Sep 12 16:27:21 2021:
(:result
 []
 :id 3 :jsonrpc "2.0")
[client-request] (id:4) Sun Sep 12 16:27:27 2021:
(:jsonrpc "2.0" :id 4 :method "textDocument/hover" :params
	  (:textDocument
	   (:uri "file:///usr/home/alex/test/test.hs")
	   :position
	   (:line 5 :character 4)))
[client-request] (id:5) Sun Sep 12 16:27:27 2021:
(:jsonrpc "2.0" :id 5 :method "textDocument/documentHighlight" :params
	  (:textDocument
	   (:uri "file:///usr/home/alex/test/test.hs")
	   :position
	   (:line 5 :character 4)))
[stderr] 2021-09-12 16:27:27.095598197 [ThreadId 102] INFO hls:	finish: Wingman.getMetaprogramsAtSpan.TypeCheck (took 0.00s)
[server-reply] (id:4) Sun Sep 12 16:27:27 2021:
(:result nil :id 4 :jsonrpc "2.0")
[server-reply] (id:5) Sun Sep 12 16:27:27 2021:
(:result
 []
 :id 5 :jsonrpc "2.0")
[client-request] (id:6) Sun Sep 12 16:27:27 2021:
(:jsonrpc "2.0" :id 6 :method "textDocument/definition" :params
	  (:textDocument
	   (:uri "file:///usr/home/alex/test/test.hs")
	   :position
	   (:line 5 :character 4)))
[server-reply] (id:6) Sun Sep 12 16:27:27 2021:
(:result
 []
 :id 6 :jsonrpc "2.0")
```
    
#### Backtrace (mandatory, unless no error message seen or heard):

    The errors is from haskell-language-server

   
#### Minimal configuration (mandatory)

     
 ```sh
emacs -Q 
 ```
 
 
 
 ```lisp
(defvar bootstrap-version)
(let ((bootstrap-file
      (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
     (bootstrap-version 5))
 (unless (file-exists-p bootstrap-file)
   (with-current-buffer
       (url-retrieve-synchronously
        "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
        'silent 'inhibit-cookies)
     (goto-char (point-max))
     (eval-print-last-sexp)))
 (load bootstrap-file nil 'nomessage))

(setq straight-use-package-by-default 't)
(straight-use-package 'use-package)

(use-package project)
(use-package eglot
  :config
  (add-hook 'haskell-mode-hook 'eglot-ensure))
(use-package haskell-mode)

  ```
 
 
### Minimal example reproducing the problem
With this haskell file:

```haskell
module main where

myFunc = print "coucou"

main = do
  myFunc
```
Going to myFunc and pressing 'M-.' (aka `xref-find-definitions`) yields `user-error: No definitions found for: LSP identifier at point.`

**Comment by leungbk** [comment]
```
[stderr] Run entered for haskell-language-server-wrapper(haskell-language-server-wrapper) Version 1.2.0.0 x86_64 ghc-8.10.7
```

GHC 8.10.6 and 8.10.7 aren't yet supported by version 1.2 of `hls` (they will be supported once 1.4 lands: https://github.com/haskell/haskell-language-server/issues/2176).

I am able to get `hls` 1.3 to work on your example file when `hls` is built with GHC 8.8.4 (the Nix package manager is quite useful for this kind of thing).

**Comment by alexDarcy** [comment]
If you can share you nix configuration, I would be happy to test.
Otherwise, `lsp-mode` works with GHC 8.10.7 to jump to definition. I'm not sure what's different with eglot.

**Comment by joaotavora** [comment]
Thanks @leungbk for having a look at this.  From what I can tell, it could be a server problem, or it could be some kind of missing configuration that can be added by the user to `eglot-workspace-configuration` for some server versions.  Of course we have to discover what that would be. @alexDarcy if you have tried this with another client and have the LSP transcript for that successful session, it would be helpful.

**Comment by alexDarcy** [comment]
Actually, eglot works with the minimal working example (there was a type : `main` should have been `Main) !
I'll try to reproduce it.

**Comment by joaotavora** [comment]
@alexDarcy So there's no suspicion of Eglot bug/misbehaviour anymore?

**Comment by alexDarcy** [comment]
After further testing, the issue is that the rootPath is set properly only with git:
Otherwise, the root is set to the folder containing the opened files so it cannot find modules properly.

This can be reproduced by creating a Haskell project with `stack new` and opening the main file.
Jumping to the definition `someFunc` from the main file works by default. It stops working when deleting the `.git` folder.

@joaotavora Is my analysis right ? Is there a way to add support for non-git VCS (I'm using darcs) ?
Thanks,

**Comment by joaotavora** [comment]
@alexDarcy I don't know if it is "right", but it does seem plausible.  Now, Eglot doesn't use Git directly to find the project root, it uses something called `project.el`, which then uses a VCS-specific adapter to find project roots, and that adapter would, I think, be able to find project roots for multiple VCS systems.  So there should, in theory, be a way for Eglot to use your Darcs home dir as the `rootPath`. I would even expect that to function automatically without any intervention.  I'll call @dgutov who is the maintainer of `project.el` and also a collaborator to Eglot, in hopes that he can shed light on the matter, as I'm not a Darcs user.

**Comment by alexDarcy** [comment]
@joaotavora You're right, `project.el` does not manage darcs repositories at the moment.

**Comment by joaotavora** [comment]
Maybe you can teach it to do that, even if just in your `.emacs`.    See the documentation for `project-find-functions` and try to type some basic Elisp for finding the Darcs root directory (maybe a special file is kept there).

In the mantime, I'm closing this, as it's not strictly Eglot-related, but we can keep discussing of course.

**Comment by dgutov** [comment]
Installing https://melpa.org/#/vc-darcs is hopefully also an option.

**Comment by alexDarcy** [comment]
@dgutov The good thing is that files are now recognized properly with Eglot (on a sample project with stack new). 
Unfortunately, the package is not useful to managed darcs repositories at the moment (I cannot do the equivalent of a commit for example).

**Comment by dgutov** [comment]
That's indeed unfortunate. The package was last updated several years ago, so if you have any skill with Elisp, maybe give it a look? The fix could be simple enough.

Here's the endpoint for creating a commit: https://github.com/velkyel/vc-darcs/blob/master/vc-darcs.el#L394-L412

**Comment by alexDarcy** [comment]
@dgutov The fix looks simple enough so I've created a PR. Thanks for the pointer.
